version: "2"
services:
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    networks:
      - mysqlnet
    volumes:
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "7080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - mysqlnet
networks:
  mysqlnet:
    driver: bridge
