services:
  cassandra-1:
    container_name: cassandra-1
    image: cassandra
    ports:
      - "9041:9042"
    #    volumes:
    #      - ./cassandra-1-data:/var/lib/cassandra
    environment:
      &environment
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_CLUSTER_NAME: bravo
      CASSANDRA_SEEDS: "cassandra-1"
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rc1
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 1s
      timeout: 5s
      retries: 60
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - ./init-scripts/demo_tables.cql:/demo_tables.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra-1 -f /demo_tables.cql"
networks:
  default:
    external:
      name: cassandra-network
